### ISSUE TITLE
identify as interactive

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/IRkernel#236]
- [ ] `options(menu.graphics = FALSE)` (#235)
- [ ] implement stdin protocol (#199)
- [ ] (maybe fits) interactive rgl session (#200)

@takluyver i’d like to add labels everywhere – could you upgrade my organization permissions please?

**Comment by janschulz** [comment]
At least stdin and input_request should be implemented for 0.7

**Comment by flying-sheep** [comment]
OK, this is pretty hard:

1. when passing `--interactive` to force the internal `R_interactive` variable to be TRUE, R crashes. No idea why, as there’s no error.
2. the R-level [`interactive()`](https://github.com/wch/r-source/blob/e5b21d0397c607883ff25cca379687b86933d730/src/main/sysutils.c#L223) function just checks that variable
3. they say [they support 4 methods of input](https://github.com/wch/r-source/blob/e5b21d0397c607883ff25cca379687b86933d730/src/gnuwin32/system.c#L166-L170) none of which resembles ours.

we might need to work with upstream R on this one.

**Comment by flying-sheep** [comment]
created a wishlist entry: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17134
