### ISSUE TITLE
Tracking other projects’ bugs that affect us

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/IRkernel#250]
* [ ] #226 Killing the kernel while it sends data is not killing the kernel completely →  
    jupyter/jupyter_client#104 subprocesses of kernels are not killed by restart
* [ ]  #184 Not all output is send to the client? →  
    hadley/evaluate#60 Not all output is captured?
* [ ] #3 Catch printed output while in a loop →  
    hadley/evaluate#62 Add possibility to flush output immediately

The idea is to keep this open / reopen it to track bugs that affect us but aren’t to fix in this project

**Comment by JanSchulz** [comment]
added #3

**Comment by JanSchulz** [comment]
Can we add a tag for this bugs, so that one can also search for them? Like "bug-upstream"?

**Comment by flying-sheep** [comment]
added the tag.

and you’d prefer them to be left open and simply tagged?

**Comment by JanSchulz** [comment]
Thanks for the tag!

re keep them open: For me, yes, for the reasons above (better add some search parameter than forgetting a bug) but I don't do the main work here and you guys should be comfortable with it :-)

**Comment by flying-sheep** [comment]
hmm, actually the label is also a good idea.

i’d rather have them collected in one issue so that the issue list doesn’t become cluttered with stuff that can’t be fixed in this repo, but al long as it’s only three issues, your alternative is also fine for me.

@takluyver what’s your opinion?

**Comment by takluyver** [comment]
I have a slight preference for tracking them as individual issues with an 'upstream bug' tag, because when I'm looking through the issue list to find something, this title is too general to be useful. Also, it's more useful to refer duplicate issues to the discussion on an individual issue than a single 'bucket' issue.

If we're sufficiently confident that it's an upstream bug, and there's nothing we can/should do to work around it, we can close those issues so that they're not cluttering up our issue list. But we don't have that many open issues, so I'm not too worried (I spent yesterday working through old IPython issues, and there are still over 900 open).

**Comment by flying-sheep** [comment]
OK
