### ISSUE TITLE
Release? 

### ISSUE THREAD

**Issue by asmeurer** [IRkernel/IRkernel#97]
It would be nice to get a release out with the changes from https://github.com/IRkernel/IRkernel/pull/84 so I could update the [conda package](http://binstar.org/r/r-irkernel). This will also help @rgbkrk with his work on tmpnb.

@JanSchulz’ TODO:
------------------------------

* [x] pull IRkernel/repr#3 Check capabilities before generating plot `repr`s
* [x] pull #99 Catch failures from `repr` and display the error
* [x] pull #100 and IRkernel/IRdisplay#7 display() API using `repr`
* [x] pull #102 'is_complete_request'
* [x] pull #105 Silence warning about comparing vectors
* [ ] generate Windows and Mac OSX binary packages on R 3.1 and 3.2 (cc: @noamross) and upload them to irkernel.github.io
* [ ] update Readme to mention OSX binary packages

Undecided bigger discussion issues still open: 
* [x] decide on scope of `repr` package (or postpone?) → IRkernel/repr#4
* [x] IRkernel/IRdisplay#6 and IRkernel/IRdisplay#8 Final discussion about 'IRdisplay' design 

For later:
* [x] IRkernel/IRdisplay#5 more `display_*` functions

**Comment by takluyver** [comment]
@flying-sheep @JanSchulz where are we with regards to tagging a release and uploading it to the repo we've now got set up? I'm not aware of anything we particularly need to do before that.

**Comment by takluyver** [comment]
Actually, we should probably change IRdisplay::display() as we discussed in IRkernel/IRdisplay#5, and then do a release.

**Comment by takluyver** [comment]
aaaand we should do something about the plot display issues described in #96 . I think it's fine to just skip pdf/svg if we don't have cairo for now.

**Comment by JanSchulz** [comment]
I would still argue that `repr` should only get the bare minimum of implmentations (basically only whatever can be printed via `print`. See here for my arguments: https://github.com/IRkernel/repr/commit/3ff5ba87b426ecaba0babe1d53925a6e08c52a3e#commitcomment-10888021

**Comment by JanSchulz** [comment]
I also think someone with knowledge of R packaging should do a `R CMD check %G%_*.tar.gz` and clean warnings/errors :-)

**Comment by JanSchulz** [comment]
I would also love to get https://github.com/IRkernel/IRkernel/issues/94 into a release

**Comment by takluyver** [comment]
To borrow a phrase from Fernando: I sense a pull request in your future. ;-)

**Comment by takluyver** [comment]
I think #98 should fix the biggest red flag from `R CMD check`

**Comment by JanSchulz** [comment]
@takluyver would that be your #98 or a very rusty one for #94 by me :-) for the latter: I'm not sure if my R is up to the coding standards here, @flying-sheep is usually baffling me with his new commits: sure, I can read and mostly understand his code, but I would have had no knowledge how to do it on my own :-)

**Comment by JanSchulz** [comment]
Oh, and another one for the Todo: wrap the mime bundle generation in a big try-except block (there is such a thing in R, I'm sure?!?), so that errors in `repr_*` do not kill the kernel (like #96).

**Comment by takluyver** [comment]
Well, R's methods stuff is rather baffling to me too. I was suggesting that you should try a pull request for #94 - from what we identified in the comments on that, I don't think it should be too complex.

The R version of a try/except block is the tryCatch function - you can see it in use where we evaluate a user's code here: https://github.com/IRkernel/IRkernel/blob/25e1955a8253163887ae329955e24366010b9a9f/R/execution.r#L138

**Comment by takluyver** [comment]
#99 should catch errors from repr failures - good call.

**Comment by takluyver** [comment]
Also, @flying-sheep @JanSchulz , we should add both of you to the authors metadata in the DESCRIPTION files for these packages. What email address would you like to use?

**Comment by JanSchulz** [comment]
#102 implements the 'is_complete_request'  and should take care of #94 

@takluyver II think it's easier if my name is not in there, as I'm mainly here from the knitpy side and not as an R dev :-)

**Comment by takluyver** [comment]
Well, I'll mainly here from the Jupyter side, not as an R dev! Up to you, but I think you've done enough to justify putting your name there.

Looking at #102 now.

**Comment by JanSchulz** [comment]
Ok, so the todo:
* [ ] pull  https://github.com/IRkernel/repr/pull/3 Check capabilities before generating plot reprs
* [ ] pull #99 Catch failures from repr and display the error
* [ ] pull #100 and https://github.com/IRkernel/IRdisplay/pull/7 display() API using repr
* [ ] pull #105 Silence warning about comparing vectors
* [x] pull #102 'is_complete_request'

Undecided bigger discussion issues still open: 
* [ ] decide on scope of `repr`package (or pospone?) -> https://github.com/IRkernel/repr/issues/4
* [ ] https://github.com/IRkernel/IRdisplay/issues/6 and https://github.com/IRkernel/IRdisplay/pull/3 Final discussion about 'IRdisplay' design 

For later:
* [ ] https://github.com/IRkernel/IRdisplay/issues/5 more display_* functions

Did I forget something? IF not, can someone (@asmeurer?) put that into the first comment of this issue?

**Comment by flying-sheep** [comment]
i’m here as a data scientist who dogfoods his report generation tool, not an R dev :wink:

please use my github profile’s email address (which i just added, so don’t be confused that you didn’t see it before :smile:)

**Comment by asmeurer** [comment]
It's worth pointing out that pretty much everyone who is using this is using `install_github`, which installs from master by default. The only people who are using a release are the people who go out of their way to install from a tag, and the people using my conda package.

**Comment by JanSchulz** [comment]
@asmeurer Hopefully afterwards, with the new r repo under irkernel.github.io, package installations (and not install_github) will be the norm... The repo will at least make is much easier for windows and OSX users...

**Comment by rgbkrk** [comment]
Just a note that I'm not going to be releasing the next try.jupyter.org until I can rely on the R kernel coming from conda. :wink:

**Comment by takluyver** [comment]
OK, I think that's everything we wanted to change in the code before releasing. Does anyone see anything else?

**Comment by flying-sheep** [comment]
there’s a bug in the kernel regarding plotting, i’ll fix it

**Comment by flying-sheep** [comment]
done, stuff actually works. should i go over everything and unify the coding style before release? some things are an eyesore.

**Comment by rgbkrk** [comment]
> should i go over everything and unify the coding style before release?

I'm basically just an outsider on this one, but I wouldn't go for large refactorings prior to the release. Ship again later. :wink:

**Comment by flying-sheep** [comment]
no refactors, just indenting and stuff. in any case i think we should go for a round of testing all kinds of things (autocompletion, plots, options, help(), and then this is ready)

**Comment by flying-sheep** [comment]
just in time, i got the page in usable shape: http://irkernel.github.io/

**Comment by JanSchulz** [comment]
SO, IMO we should update the Readme (windows and Macosx), tag a release in all repos and then upload the binaries.

**Comment by JanSchulz** [comment]
@noamross: I uploaded my drat-with-binary-support package: `install.packages("drat", repos="http://janschulz.github.io/drat/")`

This should give you `R --slave -e "drat:::insert('package_version.tgz', repodir='irkernel.github.io')"` (assuming `irkerne.github.io` is checked out in a subdir)

The complete thingy becomes (pseudo loop code...):

```
for VERSION in [3.1, 3.2]: 
  path=/path/to/R/R-$VERSION%/bin/x64;%OLDPATH%
  for PACKAGE in [rzmq,repr,IRKernel,IRDisplay]
     # R -e "R.Version()" -> this should print the right version
     R  CMD build $PACKAGE$
     R CMD check $PACKAGE$*.tar.gz
     R CMD INSTALL --build --compile-both $PACKAGE$
     R --slave -e "drat:::insert('$PACKAGE$_*.tgz', repodir='irkernel.github.io')"
```

**Comment by rgbkrk** [comment]
> just in time, i got the page in usable shape: http://irkernel.github.io/

Looking slick! It might be nice to have a screenshot of an R notebook.

**Comment by JanSchulz** [comment]
Source and Windows packages are up: https://github.com/IRkernel/irkernel.github.io/pull/5
Readme update is also up: #109

**Comment by takluyver** [comment]
I've accepted that PR and pushed the tags. Thanks everyone for responding quickly over the last couple of days!

@asmeurer , you should now be able to build conda packages for IRkernel 0.3, IRdisplay 0.3 and repr 0.1. Let us know if there are any problems.

@noamross sorry for the mixup earlier - if you're happy to build the binary packages again, we're ready now. Thanks!

**Comment by rgbkrk** [comment]
Thank you so so much.

**Comment by JanSchulz** [comment]
Status: Mac Binaries ar ebuild and in a PR -> just needs pulling https://github.com/IRkernel/irkernel.github.io/pull/6 and #109

**Comment by flying-sheep** [comment]
merged

**Comment by asmeurer** [comment]
I am getting an error when building this. 

```
+ /root/miniconda3/envs/_build/bin/R CMD INSTALL --build .
* installing to library '/root/miniconda3/envs/_build/lib/R/library'
* installing *source* package 'IRkernel' ...
** R
** inst
** preparing package for lazy loading
Error : object 'publish_mimebundle' is not exported by 'namespace:IRdisplay'
ERROR: lazy loading failed for package 'IRkernel'
* removing '/root/miniconda3/envs/_build/lib/R/library/IRkernel'
```

**Comment by takluyver** [comment]
Weird. IRdisplay says [that's exported](https://github.com/IRkernel/IRdisplay/blob/0.3/NAMESPACE#L13).

**Comment by asmeurer** [comment]
Ah, my fault. I didn't realize IRdisplay was updated as well.

**Comment by takluyver** [comment]
Yep, we did coordinated releases of all three packages. Hopefully that won't be necessary most of the time.
